name: WebApp Workflow

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: ["terraform/**"]

jobs:
  auto-provision-infra:
    name: Provision the necessary cloud resources for the web application
    runs-on: ubuntu-20.04 #ubuntu-latest
    environment: prod
    defaults:
     run:
       shell: bash
       working-directory: ./terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 0
        #   ref: ${{ github.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          # aws-region: ${{ inputs.AWS_REGION }} 
          role-to-assume: "arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/githubActionsRole"

          
      - name: Terraform Apply
        id: plan
        # if: github.event_name == 'pull_request'
        run: terraform apply
     